name = "contrabass-cloud"
main = "src/index.ts"
compatibility_date = "2026-05-08"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "CONTROL_PLANE_DB"
database_name = "contrabass-control-plane"
database_id = "ee6d3436-9997-4fcf-b241-e5aab094b729"

[[r2_buckets]]
binding = "ARTIFACTS_BUCKET"
bucket_name = "contrabass-artifacts"

[[r2_buckets]]
binding = "EVENTS_ARCHIVE_BUCKET"
bucket_name = "contrabass-events-archive"

[observability]
enabled = true
head_sampling_rate = 1.0

[env.staging]
name = "contrabass-cloud-staging"
workers_dev = true

[[env.staging.d1_databases]]
binding = "CONTROL_PLANE_DB"
database_name = "contrabass-control-plane"
database_id = "ee6d3436-9997-4fcf-b241-e5aab094b729"

[[env.staging.r2_buckets]]
binding = "ARTIFACTS_BUCKET"
bucket_name = "contrabass-artifacts"

[[env.staging.r2_buckets]]
binding = "EVENTS_ARCHIVE_BUCKET"
bucket_name = "contrabass-events-archive"

[env.staging.vars]
CONTRABASS_ENV = "staging"

[env.staging.observability]
enabled = true
head_sampling_rate = 1.0

[env.production]
name = "contrabass-cloud"
workers_dev = true

[[env.production.d1_databases]]
binding = "CONTROL_PLANE_DB"
database_name = "contrabass-control-plane"
database_id = "ee6d3436-9997-4fcf-b241-e5aab094b729"

[[env.production.r2_buckets]]
binding = "ARTIFACTS_BUCKET"
bucket_name = "contrabass-artifacts"

[[env.production.r2_buckets]]
binding = "EVENTS_ARCHIVE_BUCKET"
bucket_name = "contrabass-events-archive"

[env.production.vars]
CONTRABASS_ENV = "production"

[env.production.observability]
enabled = true
head_sampling_rate = 1.0
