// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v1

type Accept struct {
	// Accept corresponds to the JSON schema field "accept".
	Accept interface{} `json:"accept"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type ArtifactKeysFull struct {
	// Diff corresponds to the JSON schema field "diff".
	Diff R2ObjectKey `json:"diff"`

	// Logs corresponds to the JSON schema field "logs".
	Logs R2ObjectKey `json:"logs"`

	// Screenshots corresponds to the JSON schema field "screenshots".
	Screenshots []R2ObjectKey `json:"screenshots,omitempty,omitzero"`

	// Summary corresponds to the JSON schema field "summary".
	Summary R2ObjectKey `json:"summary"`
}

// Failed/cancelled runs may not have produced all artifacts; any subset is
// allowed.
type ArtifactKeysPartial struct {
	// Diff corresponds to the JSON schema field "diff".
	Diff *R2ObjectKey `json:"diff,omitempty,omitzero"`

	// Logs corresponds to the JSON schema field "logs".
	Logs *R2ObjectKey `json:"logs,omitempty,omitzero"`

	// Screenshots corresponds to the JSON schema field "screenshots".
	Screenshots []R2ObjectKey `json:"screenshots,omitempty,omitzero"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *R2ObjectKey `json:"summary,omitempty,omitzero"`
}

type AuthInvalidError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type BaseFields struct {
	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Monotonic per-run sequence number assigned by the worker. Optional but
	// recommended for replay deduplication.
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type BearerToken string

type CancelledCompletion struct {
	// ArtifactKeys corresponds to the JSON schema field "artifactKeys".
	ArtifactKeys ArtifactKeysPartial `json:"artifactKeys"`

	// FinalConfigHash corresponds to the JSON schema field "finalConfigHash".
	FinalConfigHash ConfigHash `json:"finalConfigHash"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Status corresponds to the JSON schema field "status".
	Status interface{} `json:"status"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`
}

// Examples: agent:codex, agent:opencode, tmux, git, os:darwin, arch:arm64
type Capability string

// Bare 64-char SHA-256 hex digest of the active workflow YAML.
// Content-addressable; safe in URL path parameters (no colon).
type ConfigHash string

type DiffEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload DiffEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type DiffEventPayload struct {
	// Additions corresponds to the JSON schema field "additions".
	Additions *int `json:"additions,omitempty,omitzero"`

	// Deletions corresponds to the JSON schema field "deletions".
	Deletions *int `json:"deletions,omitempty,omitzero"`

	// FilesChanged corresponds to the JSON schema field "filesChanged".
	FilesChanged int `json:"filesChanged"`

	// Optional inline summary; full diff goes to R2 via the dispatch presigned URL.
	Summary *string `json:"summary,omitempty,omitzero"`
}

// Milliseconds since Unix epoch.
type EpochMillis int

type ErrorCode string

const ErrorCodeLeaseAlreadyHeld ErrorCode = "lease_already_held"
const ErrorCodeLeaseRevoked ErrorCode = "lease_revoked"
const ErrorCodeRunUnknown ErrorCode = "run_unknown"

type ErrorCode_1 string

const ErrorCode_1_ArtifactMissing ErrorCode_1 = "artifact_missing"
const ErrorCode_1_LeaseHolderMismatch ErrorCode_1 = "lease_holder_mismatch"
const ErrorCode_1_LeaseRevoked ErrorCode_1 = "lease_revoked"
const ErrorCode_1_RunTerminal ErrorCode_1 = "run_terminal"
const ErrorCode_1_RunUnknown ErrorCode_1 = "run_unknown"

type ErrorCode_2 string

const ErrorCode_2_EventsTooLarge ErrorCode_2 = "events_too_large"
const ErrorCode_2_EventsTooMany ErrorCode_2 = "events_too_many"
const ErrorCode_2_InvalidNDJSON ErrorCode_2 = "invalid_ndjson"
const ErrorCode_2_LeaseRevoked ErrorCode_2 = "lease_revoked"
const ErrorCode_2_RunTerminal ErrorCode_2 = "run_terminal"
const ErrorCode_2_RunUnknown ErrorCode_2 = "run_unknown"

type ErrorCode_3 string

const ErrorCode_3_LeaseHolderMismatch ErrorCode_3 = "lease_holder_mismatch"
const ErrorCode_3_LeaseRevoked ErrorCode_3 = "lease_revoked"
const ErrorCode_3_RunTerminal ErrorCode_3 = "run_terminal"
const ErrorCode_3_RunUnknown ErrorCode_3 = "run_unknown"

type ErrorCode_4 string

const ErrorCode_4_RefreshExpired ErrorCode_4 = "refresh_expired"
const ErrorCode_4_RefreshInvalid ErrorCode_4 = "refresh_invalid"
const ErrorCode_4_RefreshRevoked ErrorCode_4 = "refresh_revoked"

type ErrorCode_5 string

const ErrorCode_5_AuthInvalid ErrorCode_5 = "auth_invalid"
const ErrorCode_5_ProtocolVersionUnsupported ErrorCode_5 = "protocol_version_unsupported"
const ErrorCode_5_TeamForbidden ErrorCode_5 = "team_forbidden"
const ErrorCode_5_TeamWorkerCapExceeded ErrorCode_5 = "team_worker_cap_exceeded"

type ErrorEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload ErrorEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type ErrorEventPayload struct {
	// ErrorClass corresponds to the JSON schema field "errorClass".
	ErrorClass string `json:"errorClass"`

	// Fatal corresponds to the JSON schema field "fatal".
	Fatal bool `json:"fatal,omitempty,omitzero"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

// Generic error envelope. Per-endpoint files define concrete error response
// schemas with additionalProperties: false and any structured fields the spec
// calls out (e.g., supported, max_events, max_bytes).
type ErrorResponseBase struct {
	// Stable error code (snake_case). Per-endpoint enums in their own files.
	Error string `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// HTTP 413 body. Mirrors spec scenario 'Worker exceeds per-request event limits'.
type EventsTooLargeError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// MaxBytes corresponds to the JSON schema field "max_bytes".
	MaxBytes interface{} `json:"max_bytes"`

	// MaxEvents corresponds to the JSON schema field "max_events".
	MaxEvents interface{} `json:"max_events"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type EventsTooManyError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// MaxEvents corresponds to the JSON schema field "max_events".
	MaxEvents interface{} `json:"max_events"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type FailedCompletion struct {
	// ArtifactKeys corresponds to the JSON schema field "artifactKeys".
	ArtifactKeys ArtifactKeysPartial `json:"artifactKeys"`

	// Stable error category (e.g., 'agent_runner_crash', 'tests_failed',
	// 'merge_conflict').
	ErrorClass string `json:"errorClass"`

	// FinalConfigHash corresponds to the JSON schema field "finalConfigHash".
	FinalConfigHash ConfigHash `json:"finalConfigHash"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Status corresponds to the JSON schema field "status".
	Status interface{} `json:"status"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`
}

// Git ref-name subset: rejects '..', leading dot per segment, '.lock' suffix, and
// trailing '.' or '/'.
type GitBranch string

type InvalidNDJSONError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// LineNumber corresponds to the JSON schema field "lineNumber".
	LineNumber int `json:"lineNumber"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

// Tracker-native issue identifier (e.g., LIN-123, owner/repo#42, internal-board
// UUID). Pattern rejects leading whitespace/control chars to keep dashboard, log,
// and R2-key derivation safe.
type IssueRef string

type LeaseAlreadyHeldError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type LeaseHolderMismatchError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type LeaseRevokedError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

// Server-to-worker WebSocket frame revoking the lease for a run. See
// worker-protocol spec: 'Lease revocation push'. On receipt the worker MUST stop
// the agent (SIGTERM, then SIGKILL after 5s), attempt artifact upload to
// still-valid presigned URLs, and discard local state for the run.
type LeaseRevokedFrame struct {
	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Reason corresponds to the JSON schema field "reason".
	Reason LeaseRevokedFrameReason `json:"reason"`

	// Optional human-readable detail (e.g., admin name on worker_evicted_by_admin).
	ReasonDetail *string `json:"reasonDetail,omitempty,omitzero"`

	// RevokedAt corresponds to the JSON schema field "revokedAt".
	RevokedAt *EpochMillis `json:"revokedAt,omitempty,omitzero"`

	// RunID corresponds to the JSON schema field "runId".
	RunID RunID `json:"runId"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type LeaseRevokedFrameReason string

const LeaseRevokedFrameReasonAckTimeout LeaseRevokedFrameReason = "ack_timeout"
const LeaseRevokedFrameReasonCancelled LeaseRevokedFrameReason = "cancelled"
const LeaseRevokedFrameReasonConfigInvalidated LeaseRevokedFrameReason = "config_invalidated"
const LeaseRevokedFrameReasonHeartbeatTimeout LeaseRevokedFrameReason = "heartbeat_timeout"
const LeaseRevokedFrameReasonManualReassign LeaseRevokedFrameReason = "manual_reassign"
const LeaseRevokedFrameReasonProtocolVersionRenegotiation LeaseRevokedFrameReason = "protocol_version_renegotiation"
const LeaseRevokedFrameReasonServerShutdown LeaseRevokedFrameReason = "server_shutdown"
const LeaseRevokedFrameReasonSessionExpired LeaseRevokedFrameReason = "session_expired"
const LeaseRevokedFrameReasonTeamPaused LeaseRevokedFrameReason = "team_paused"
const LeaseRevokedFrameReasonWorkerEvictedByAdmin LeaseRevokedFrameReason = "worker_evicted_by_admin"

// Lease duration in seconds. Wire-level bound is 4 hours; per-team config may set
// lower limits. Server authoritative; worker echoes for diagnostics only.
type LeaseSec int

// Server-enforced limits (informational; HTTP-byte-counted, not part of array
// contract).
type Limits struct {
	// MaxBytesPerRequest corresponds to the JSON schema field "maxBytesPerRequest".
	MaxBytesPerRequest interface{} `json:"maxBytesPerRequest,omitempty,omitzero"`

	// MaxEventsPerRequest corresponds to the JSON schema field "maxEventsPerRequest".
	MaxEventsPerRequest interface{} `json:"maxEventsPerRequest,omitempty,omitzero"`
}

type LogEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload LogEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type LogEventPayload struct {
	// Level corresponds to the JSON schema field "level".
	Level LogEventPayloadLevel `json:"level"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Optional source tag (e.g., 'agent', 'runner', 'tmux').
	Source *string `json:"source,omitempty,omitzero"`
}

type LogEventPayloadLevel string

const LogEventPayloadLevelDebug LogEventPayloadLevel = "debug"
const LogEventPayloadLevelError LogEventPayloadLevel = "error"
const LogEventPayloadLevelInfo LogEventPayloadLevel = "info"
const LogEventPayloadLevelWarn LogEventPayloadLevel = "warn"

type PhaseEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload PhaseEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type PhaseEventPayload struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero"`

	// Phase corresponds to the JSON schema field "phase".
	Phase PhaseEventPayloadPhase `json:"phase"`
}

type PhaseEventPayloadPhase string

const PhaseEventPayloadPhaseComplete PhaseEventPayloadPhase = "complete"
const PhaseEventPayloadPhaseExec PhaseEventPayloadPhase = "exec"
const PhaseEventPayloadPhasePlan PhaseEventPayloadPhase = "plan"
const PhaseEventPayloadPhaseReview PhaseEventPayloadPhase = "review"
const PhaseEventPayloadPhaseVerify PhaseEventPayloadPhase = "verify"

// Frozen wire identifier for v1. Locked per design D2.
type ProtocolVersion string

// HTTP 409 body. Mirrors spec scenario 'Worker advertises an incompatible major
// version'.
type ProtocolVersionUnsupportedError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Supported corresponds to the JSON schema field "supported".
	Supported []ProtocolVersion `json:"supported"`
}

type R2ObjectKey string

type RefreshExpiredError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type RefreshInvalidError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type RefreshRevokedError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type Reject struct {
	// Accept corresponds to the JSON schema field "accept".
	Accept interface{} `json:"accept"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Reason corresponds to the JSON schema field "reason".
	Reason RejectReason `json:"reason"`

	// ReasonDetail corresponds to the JSON schema field "reasonDetail".
	ReasonDetail *string `json:"reasonDetail,omitempty,omitzero"`
}

type RejectReason string

const RejectReasonAtCapacity RejectReason = "at_capacity"
const RejectReasonConfigHashUnknown RejectReason = "config_hash_unknown"
const RejectReasonMissingCapability RejectReason = "missing_capability"
const RejectReasonOther RejectReason = "other"
const RejectReasonWorkerShuttingDown RejectReason = "worker_shutting_down"

type RunID string

type RunTerminalError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type RunUnknownError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type StartEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload StartEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type StartEventPayload struct {
	// Which runner started: codex|opencode|omx|omc|mock|other.
	AgentRunner string `json:"agentRunner"`

	// Branch corresponds to the JSON schema field "branch".
	Branch *GitBranch `json:"branch,omitempty,omitzero"`

	// WorktreePath corresponds to the JSON schema field "worktreePath".
	WorktreePath *string `json:"worktreePath,omitempty,omitzero"`
}

type SucceededCompletion struct {
	// ArtifactKeys corresponds to the JSON schema field "artifactKeys".
	ArtifactKeys ArtifactKeysFull `json:"artifactKeys"`

	// FinalConfigHash corresponds to the JSON schema field "finalConfigHash".
	FinalConfigHash ConfigHash `json:"finalConfigHash"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Status corresponds to the JSON schema field "status".
	Status interface{} `json:"status"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`
}

type TeamForbiddenError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type TeamID string

type TeamWorkerCapExceededError struct {
	// Error corresponds to the JSON schema field "error".
	Error interface{} `json:"error"`

	// MaxActiveWorkers corresponds to the JSON schema field "max_active_workers".
	MaxActiveWorkers int `json:"max_active_workers"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type ToolCallEvent struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload ToolCallEventPayload `json:"payload"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// Seq corresponds to the JSON schema field "seq".
	Seq *int `json:"seq,omitempty,omitzero"`

	// Ts corresponds to the JSON schema field "ts".
	Ts EpochMillis `json:"ts"`
}

type ToolCallEventPayload struct {
	// Argument summary; truncate before send. Free-form.
	Args interface{} `json:"args,omitempty,omitzero"`

	// OutputSummary corresponds to the JSON schema field "outputSummary".
	OutputSummary *string `json:"outputSummary,omitempty,omitzero"`

	// Phase corresponds to the JSON schema field "phase".
	Phase ToolCallEventPayloadPhase `json:"phase"`

	// TokensIn corresponds to the JSON schema field "tokensIn".
	TokensIn *int `json:"tokensIn,omitempty,omitzero"`

	// TokensOut corresponds to the JSON schema field "tokensOut".
	TokensOut *int `json:"tokensOut,omitempty,omitzero"`

	// Tool corresponds to the JSON schema field "tool".
	Tool string `json:"tool"`
}

type ToolCallEventPayloadPhase string

const ToolCallEventPayloadPhaseError ToolCallEventPayloadPhase = "error"
const ToolCallEventPayloadPhaseResult ToolCallEventPayloadPhase = "result"
const ToolCallEventPayloadPhaseStart ToolCallEventPayloadPhase = "start"

type URL string

// Server-to-worker dispatch payload. Sent over WebSocket as a single text frame
// ({type: 'dispatch', ...}) and reused as the JSON body of GET
// /v1/workers/{workerId}/dispatch?wait=25s long-poll responses. See
// worker-protocol spec: 'Dispatch over WebSocket', 'Long-poll dispatch fallback'.
type WorkerDispatchFrame struct {
	// Seconds the cloud waits for an ack before revoking the lease.
	AckDeadlineSec int `json:"ackDeadlineSec,omitempty,omitzero"`

	// R2 presigned PUT URLs valid for the lease duration. Workers MUST upload large
	// outputs here, NOT via the events endpoint.
	ArtifactUploadURLs WorkerDispatchFrameArtifactUploadURLs `json:"artifactUploadURLs"`

	// Branch corresponds to the JSON schema field "branch".
	Branch GitBranch `json:"branch"`

	// ConfigHash corresponds to the JSON schema field "configHash".
	ConfigHash ConfigHash `json:"configHash"`

	// DispatchedAt corresponds to the JSON schema field "dispatchedAt".
	DispatchedAt *EpochMillis `json:"dispatchedAt,omitempty,omitzero"`

	// IssueRef corresponds to the JSON schema field "issueRef".
	IssueRef IssueRef `json:"issueRef"`

	// LeaseSec corresponds to the JSON schema field "leaseSec".
	LeaseSec LeaseSec `json:"leaseSec"`

	// Rendered Liquid template from active config (no secret references).
	Prompt string `json:"prompt"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// RunID corresponds to the JSON schema field "runId".
	RunID RunID `json:"runId"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// R2 presigned PUT URLs valid for the lease duration. Workers MUST upload large
// outputs here, NOT via the events endpoint.
type WorkerDispatchFrameArtifactUploadURLs struct {
	// Diff corresponds to the JSON schema field "diff".
	Diff URL `json:"diff"`

	// Logs corresponds to the JSON schema field "logs".
	Logs URL `json:"logs"`

	// Screenshots corresponds to the JSON schema field "screenshots".
	Screenshots []URL `json:"screenshots,omitempty,omitzero"`

	// Summary corresponds to the JSON schema field "summary".
	Summary URL `json:"summary"`
}

// Schema for ONE NDJSON line of POST /v1/runs/{runId}/events (Content-Type:
// application/x-ndjson). Per-kind payload shapes are sealed via discriminated
// oneOf. The endpoint accepts up to 200 lines or 512 KiB total per request — see
// events-request.json for the logical batch contract used by tests and golden
// fixtures.
type WorkerEventLine map[string]interface{}

// Logical decoded form of POST /v1/runs/{runId}/events for tests and golden
// fixtures. The wire format is NDJSON (Content-Type: application/x-ndjson, one
// JSON object per line). The maxBytes server invariant (524288) is HTTP-byte
// counted and cannot be enforced by JSON Schema — see events.json $defs.Limits.
type WorkerEventsRequest []WorkerEventLine

// POST /v1/runs/{runId}/heartbeat — worker extends the lease for an active run.
// Cadence ≤ heartbeatIntervalSec from register response. See worker-protocol spec:
// 'Heartbeat and lease extension'.
type WorkerHeartbeatRequest struct {
	// LastEventTs corresponds to the JSON schema field "lastEventTs".
	LastEventTs EpochMillis `json:"lastEventTs"`

	// Short human-readable phase label (e.g., 'planning', 'editing', 'verifying').
	Progress *string `json:"progress,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`
}

type WorkerID string

// POST /v1/workers/refresh request body. See worker-protocol spec: 'Session
// refresh'.
type WorkerRefreshRequest struct {
	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// RefreshToken corresponds to the JSON schema field "refreshToken".
	RefreshToken BearerToken `json:"refreshToken"`
}

// POST /v1/workers/refresh success response (HTTP 200) and structured error
// response shapes.
type WorkerRefreshResponse struct {
	// ExpiresAt corresponds to the JSON schema field "expiresAt".
	ExpiresAt EpochMillis `json:"expiresAt"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// SessionToken corresponds to the JSON schema field "sessionToken".
	SessionToken BearerToken `json:"sessionToken"`
}

// POST /v1/workers/register request body. See worker-protocol spec: 'Worker
// registration and session bootstrap', 'Versioned protocol identity'.
type WorkerRegisterRequest struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []Capability `json:"capabilities"`

	// Optional self-declared worker type. Cloud uses for selection policy. Phase 2
	// sets 'container'.
	Kind WorkerRegisterRequestKind `json:"kind,omitempty,omitzero"`

	// Maximum number of concurrently-acked runs the worker accepts.
	MaxConcurrency int `json:"maxConcurrency"`

	// Semver list of protocol versions this worker can speak. Cloud picks one (1.0.0
	// in v1).
	SupportedProtocolVersions []string `json:"supported_protocol_versions"`

	// TeamID corresponds to the JSON schema field "teamId".
	TeamID TeamID `json:"teamId"`

	// Worker build version (e.g., contrabass git sha or semver).
	Version string `json:"version"`

	// WorkerID corresponds to the JSON schema field "workerId".
	WorkerID WorkerID `json:"workerId"`
}

type WorkerRegisterRequestKind string

const WorkerRegisterRequestKindContainer WorkerRegisterRequestKind = "container"
const WorkerRegisterRequestKindLocal WorkerRegisterRequestKind = "local"

// POST /v1/workers/register success response (HTTP 200) and structured error
// response shapes.
type WorkerRegisterResponse struct {
	// DispatchChannel corresponds to the JSON schema field "dispatchChannel".
	DispatchChannel WorkerRegisterResponseDispatchChannel `json:"dispatchChannel"`

	// Cadence (seconds) at which the worker MUST send heartbeats per active run.
	HeartbeatIntervalSec int `json:"heartbeatIntervalSec"`

	// LeaseSec corresponds to the JSON schema field "leaseSec".
	LeaseSec LeaseSec `json:"leaseSec"`

	// ProtocolVersion corresponds to the JSON schema field "protocol_version".
	ProtocolVersion ProtocolVersion `json:"protocol_version"`

	// RefreshToken corresponds to the JSON schema field "refreshToken".
	RefreshToken BearerToken `json:"refreshToken"`

	// SessionToken corresponds to the JSON schema field "sessionToken".
	SessionToken BearerToken `json:"sessionToken"`

	// Wall-clock millis when the sessionToken expires. Workers SHOULD refresh ahead
	// of this point via /v1/workers/refresh.
	SessionTokenExpiresAt EpochMillis `json:"sessionTokenExpiresAt"`
}

type WorkerRegisterResponseDispatchChannel struct {
	// LongPollURL corresponds to the JSON schema field "longPollUrl".
	LongPollURL URL `json:"longPollUrl"`

	// WsURL corresponds to the JSON schema field "wsUrl".
	WsURL WsURL `json:"wsUrl"`
}

type WsURL string
