/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /v1/runs/{runId}/ack — worker accepts or rejects a dispatch within ackDeadlineSec (default 5s). See worker-protocol spec: 'Dispatch acknowledgement'. The schema discriminates on `accept` so codegen produces a sealed union of Accept/Reject.
 */
export type WorkerAckRequest = Accept | Reject;

export interface Accept {
  accept: true;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export interface Reject {
  accept: false;
  reason: "at_capacity" | "missing_capability" | "config_hash_unknown" | "worker_shutting_down" | "other";
  reasonDetail?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
