/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /v1/runs/{runId}/complete — worker reports terminal state. See worker-protocol spec: 'Run completion'. Discriminated on `status` so codegen produces a sealed union; `errorClass` is required only on failed completions, and `artifactKeys` is required only on successful completions.
 */
export type WorkerCompleteRequest = SucceededCompletion | FailedCompletion | CancelledCompletion;
export type R2ObjectKey = string;

export interface SucceededCompletion {
  status: "succeeded";
  summary: string;
  artifactKeys: ArtifactKeysFull;
  /**
   * Bare 64-char SHA-256 hex digest of the active workflow YAML. Content-addressable; safe in URL path parameters (no colon).
   */
  finalConfigHash: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export interface ArtifactKeysFull {
  logs: R2ObjectKey;
  diff: R2ObjectKey;
  summary: R2ObjectKey;
  /**
   * @minItems 0
   * @maxItems 32
   */
  screenshots?: R2ObjectKey[];
}
export interface FailedCompletion {
  status: "failed";
  summary: string;
  /**
   * Stable error category (e.g., 'agent_runner_crash', 'tests_failed', 'merge_conflict').
   */
  errorClass: string;
  artifactKeys: ArtifactKeysPartial;
  /**
   * Bare 64-char SHA-256 hex digest of the active workflow YAML. Content-addressable; safe in URL path parameters (no colon).
   */
  finalConfigHash: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * Failed/cancelled runs may not have produced all artifacts; any subset is allowed.
 */
export interface ArtifactKeysPartial {
  logs?: R2ObjectKey;
  diff?: R2ObjectKey;
  summary?: R2ObjectKey;
  /**
   * @minItems 0
   * @maxItems 32
   */
  screenshots?: R2ObjectKey[];
}
export interface CancelledCompletion {
  status: "cancelled";
  summary: string;
  artifactKeys: ArtifactKeysPartial;
  /**
   * Bare 64-char SHA-256 hex digest of the active workflow YAML. Content-addressable; safe in URL path parameters (no colon).
   */
  finalConfigHash: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
