/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Server-to-worker dispatch payload. Sent over WebSocket as a single text frame ({type: 'dispatch', ...}) and reused as the JSON body of GET /v1/workers/{workerId}/dispatch?wait=25s long-poll responses. See worker-protocol spec: 'Dispatch over WebSocket', 'Long-poll dispatch fallback'.
 */
export interface WorkerDispatchFrame {
  type: "dispatch";
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  runId: string;
  /**
   * Tracker-native issue identifier (e.g., LIN-123, owner/repo#42, internal-board UUID). Pattern rejects leading whitespace/control chars to keep dashboard, log, and R2-key derivation safe.
   */
  issueRef: string;
  /**
   * Git ref-name subset: rejects '..', leading dot per segment, '.lock' suffix, and trailing '.' or '/'.
   */
  branch: string;
  /**
   * Rendered Liquid template from active config (no secret references).
   */
  prompt: string;
  /**
   * Bare 64-char SHA-256 hex digest of the active workflow YAML. Content-addressable; safe in URL path parameters (no colon).
   */
  configHash: string;
  /**
   * Lease duration in seconds. Wire-level bound is 4 hours; per-team config may set lower limits. Server authoritative; worker echoes for diagnostics only.
   */
  leaseSec: number;
  /**
   * Seconds the cloud waits for an ack before revoking the lease.
   */
  ackDeadlineSec?: number;
  /**
   * R2 presigned PUT URLs valid for the lease duration. Workers MUST upload large outputs here, NOT via the events endpoint.
   */
  artifactUploadURLs: {
    logs: string;
    diff: string;
    summary: string;
    /**
     * @minItems 0
     * @maxItems 32
     */
    screenshots?: string[];
  };
  /**
   * Milliseconds since Unix epoch.
   */
  dispatchedAt?: number;
}
