/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for ONE NDJSON line of POST /v1/runs/{runId}/events (Content-Type: application/x-ndjson). Per-kind payload shapes are sealed via discriminated oneOf. The endpoint accepts up to 200 lines or 512 KiB total per request — see events-request.json for the logical batch contract used by tests and golden fixtures.
 */
export type WorkerEventLine = StartEvent | LogEvent | ToolCallEvent | DiffEvent | ErrorEvent | PhaseEvent;

export interface StartEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "start";
  payload: {
    /**
     * Which runner started: codex|opencode|omx|omc|mock|other.
     */
    agentRunner: string;
    worktreePath?: string;
    /**
     * Git ref-name subset: rejects '..', leading dot per segment, '.lock' suffix, and trailing '.' or '/'.
     */
    branch?: string;
  };
}
export interface LogEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "log";
  payload: {
    level: "debug" | "info" | "warn" | "error";
    message: string;
    /**
     * Optional source tag (e.g., 'agent', 'runner', 'tmux').
     */
    source?: string;
  };
}
export interface ToolCallEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "tool_call";
  payload: {
    tool: string;
    phase: "start" | "result" | "error";
    /**
     * Argument summary; truncate before send. Free-form.
     */
    args?:
      | {
          [k: string]: unknown;
        }
      | string
      | null;
    outputSummary?: string;
    tokensIn?: number;
    tokensOut?: number;
  };
}
export interface DiffEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "diff";
  payload: {
    filesChanged: number;
    additions?: number;
    deletions?: number;
    /**
     * Optional inline summary; full diff goes to R2 via the dispatch presigned URL.
     */
    summary?: string;
  };
}
export interface ErrorEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "error";
  payload: {
    errorClass: string;
    message: string;
    fatal?: boolean;
  };
}
export interface PhaseEvent {
  /**
   * Milliseconds since Unix epoch.
   */
  ts: number;
  seq?: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  kind: "phase";
  payload: {
    phase: "plan" | "exec" | "verify" | "review" | "complete";
    label?: string;
  };
}
