/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `WorkerHeartbeatRequest`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode = "lease_revoked" | "lease_holder_mismatch" | "run_unknown" | "run_terminal";
export type WorkerHeartbeatErrorResponse =
  | LeaseRevokedError
  | LeaseHolderMismatchError
  | RunUnknownError
  | RunTerminalError;

/**
 * POST /v1/runs/{runId}/heartbeat — worker extends the lease for an active run. Cadence ≤ heartbeatIntervalSec from register response. See worker-protocol spec: 'Heartbeat and lease extension'.
 */
export interface WorkerHeartbeatRequest {
  /**
   * Short human-readable phase label (e.g., 'planning', 'editing', 'verifying').
   */
  progress?: string;
  /**
   * Milliseconds since Unix epoch.
   */
  lastEventTs: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerHeartbeatRequest`'s JSON-Schema
 * via the `definition` "LeaseRevokedError".
 */
export interface LeaseRevokedError {
  error: "lease_revoked";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerHeartbeatRequest`'s JSON-Schema
 * via the `definition` "LeaseHolderMismatchError".
 */
export interface LeaseHolderMismatchError {
  error: "lease_holder_mismatch";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerHeartbeatRequest`'s JSON-Schema
 * via the `definition` "RunUnknownError".
 */
export interface RunUnknownError {
  error: "run_unknown";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerHeartbeatRequest`'s JSON-Schema
 * via the `definition` "RunTerminalError".
 */
export interface RunTerminalError {
  error: "run_terminal";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
