/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Server-to-worker WebSocket frame revoking the lease for a run. See worker-protocol spec: 'Lease revocation push'. On receipt the worker MUST stop the agent (SIGTERM, then SIGKILL after 5s), attempt artifact upload to still-valid presigned URLs, and discard local state for the run.
 */
export interface LeaseRevokedFrame {
  type: "lease-revoked";
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  runId: string;
  reason:
    | "heartbeat_timeout"
    | "ack_timeout"
    | "manual_reassign"
    | "cancelled"
    | "team_paused"
    | "config_invalidated"
    | "server_shutdown"
    | "worker_evicted_by_admin"
    | "session_expired"
    | "protocol_version_renegotiation";
  /**
   * Optional human-readable detail (e.g., admin name on worker_evicted_by_admin).
   */
  reasonDetail?: string;
  /**
   * Milliseconds since Unix epoch.
   */
  revokedAt?: number;
}
