/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `WorkerRefreshResponse`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode = "refresh_revoked" | "refresh_expired" | "refresh_invalid";
export type WorkerRefreshErrorResponse = RefreshRevokedError | RefreshExpiredError | RefreshInvalidError;

/**
 * POST /v1/workers/refresh success response (HTTP 200) and structured error response shapes.
 */
export interface WorkerRefreshResponse {
  sessionToken: string;
  /**
   * Milliseconds since Unix epoch.
   */
  expiresAt: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerRefreshResponse`'s JSON-Schema
 * via the `definition` "RefreshRevokedError".
 */
export interface RefreshRevokedError {
  error: "refresh_revoked";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerRefreshResponse`'s JSON-Schema
 * via the `definition` "RefreshExpiredError".
 */
export interface RefreshExpiredError {
  error: "refresh_expired";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
/**
 * This interface was referenced by `WorkerRefreshResponse`'s JSON-Schema
 * via the `definition` "RefreshInvalidError".
 */
export interface RefreshInvalidError {
  error: "refresh_invalid";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
