/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /v1/workers/register request body. See worker-protocol spec: 'Worker registration and session bootstrap', 'Versioned protocol identity'.
 */
export interface WorkerRegisterRequest {
  teamId: string;
  workerId: string;
  /**
   * @minItems 1
   * @maxItems 64
   */
  capabilities: [string, ...string[]];
  /**
   * Maximum number of concurrently-acked runs the worker accepts.
   */
  maxConcurrency: number;
  /**
   * Worker build version (e.g., contrabass git sha or semver).
   */
  version: string;
  /**
   * Semver list of protocol versions this worker can speak. Cloud picks one (1.0.0 in v1).
   *
   * @minItems 1
   * @maxItems 16
   */
  supported_protocol_versions:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
  /**
   * Optional self-declared worker type. Cloud uses for selection policy. Phase 2 sets 'container'.
   */
  kind?: "local" | "container";
}
