/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * POST /v1/workers/register success response (HTTP 200) and structured error response shapes.
 */
export interface WorkerRegisterResponse {
  sessionToken: string;
  /**
   * Wall-clock millis when the sessionToken expires. Workers SHOULD refresh ahead of this point via /v1/workers/refresh.
   */
  sessionTokenExpiresAt: number;
  refreshToken: string;
  dispatchChannel: {
    wsUrl: string;
    longPollUrl: string;
  };
  /**
   * Cadence (seconds) at which the worker MUST send heartbeats per active run.
   */
  heartbeatIntervalSec: number;
  /**
   * Lease duration in seconds. Wire-level bound is 4 hours; per-team config may set lower limits. Server authoritative; worker echoes for diagnostics only.
   */
  leaseSec: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export type WorkerRegisterErrorResponse =
  | ProtocolVersionUnsupportedError
  | TeamForbiddenError
  | TeamWorkerCapExceededError
  | AuthInvalidError;

/**
 * HTTP 409 body. Mirrors spec scenario 'Worker advertises an incompatible major version'.
 */
export interface ProtocolVersionUnsupportedError {
  error: "protocol_version_unsupported";
  message?: string;
  /**
   * @minItems 1
   */
  supported: ["1.0.0", ...("1.0.0")[]];
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export interface TeamForbiddenError {
  error: "team_forbidden";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export interface TeamWorkerCapExceededError {
  error: "team_worker_cap_exceeded";
  message?: string;
  max_active_workers: number;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
export interface AuthInvalidError {
  error: "auth_invalid";
  message?: string;
  /**
   * Frozen wire identifier for v1. Locked per design D2.
   */
  protocol_version: "1.0.0";
}
